
const char *test_text[] = {
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales lectus id eros tempus, in ultrices libero dictum. Suspendisse quis eleifend felis, in convallis enim. Etiam malesuada non dui non dapibus. Vivamus eget tempor elit, quis auctor massa. Maecenas metus orci, mollis ultricies magna eget, iaculis porttitor diam. Fusce pretium odio tristique elit suscipit mattis. Mauris placerat, orci sed pharetra volutpat, leo turpis dignissim urna, eu ultricies magna diam et dui.\n\nIn hac habitasse platea dictumst. Proin non ante libero. Proin dignissim accumsan sapien, sed aliquam felis euismod vitae. Proin ut velit consequat, congue lorem eu, condimentum odio. Etiam tempus pellentesque ante vel tempus. Maecenas scelerisque dolor vitae tortor eleifend cursus. Donec vitae suscipit urna, eu eleifend mauris. Nulla nibh tortor, tempor eget imperdiet feugiat, ultricies a diam. Donec tellus magna, molestie at eros ultrices, auctor ullamcorper felis. Curabitur blandit sem et tellus tincidunt, et aliquam quam scelerisque. Nulla pretium scelerisque vestibulum. Sed commodo laoreet sem, id tempus turpis vehicula eu. Suspendisse est nibh, pellentesque et orci eget, euismod ultricies lorem.",
  "Quisque in sagittis eros. Quisque felis neque, ornare ac purus vel, vestibulum efficitur purus. Phasellus pellentesque justo et eleifend auctor. Suspendisse accumsan nulla nec mollis laoreet. Sed ultricies id tellus ut elementum. Aenean maximus leo orci, eget gravida ipsum sodales sit amet. Duis in metus eu ante scelerisque luctus. Ut consequat pharetra tempor. Fusce elementum velit eu elementum tristique. Vivamus eget orci turpis. Aenean euismod erat sit amet mattis tincidunt. Nulla convallis cursus tempor. Integer sed rutrum enim, id suscipit massa.\n\nProin cursus suscipit enim, eget bibendum est faucibus sit amet. Donec id lectus nec nunc dictum placerat. Praesent tempor ut lorem non finibus. Sed ac libero ultricies, finibus turpis eu, elementum elit. Curabitur eleifend fringilla sapien, eget vehicula elit ullamcorper ultrices. Suspendisse potenti. Cras est velit, pretium at bibendum ac, hendrerit viverra ante. Sed nec ullamcorper leo, a tempus sem. Cras non elit a ipsum congue hendrerit. Etiam eget malesuada lectus, nec cursus massa. Sed tincidunt felis id purus elementum lobortis."
};

const char *instructions[] = {
  "Vault B42 is secret base hidden near the border of Czech Republic and Germany. It's main purpose is nearby area monitoring (radius 30Km). All weird and suspicious activity must be logged in and reported via security infrastructure.\n\nBase launch bay also houses several nuclear warheads. These can be fired from remote locations as well as from local launch center. Warheads can be fired only with special clearance and with appropriate security keys.\n\nOther information can be found at your Vault operation manual or communicated via communication terminal."
};


